version: '2.3'

services:
    cscd70-dev:
        image: cscd70:6.0
        build:
            context: ./0-CSCD70_Docker
            dockerfile: cscd70.Dockerfile
        volumes:
            - .:/mnt
        working_dir: /mnt
